package com.qnz.bms.mapper;

import com.qnz.bms.domain.AreaCode;
import com.qnz.bms.domain.AreaCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    long countByExample(AreaCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int deleteByExample(AreaCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int insert(AreaCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int insertSelective(AreaCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    List<AreaCode> selectByExample(AreaCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    AreaCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AreaCode record, @Param("example") AreaCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AreaCode record, @Param("example") AreaCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AreaCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AreaCode record);
}