package com.qnz.bms.mapper;

import com.qnz.bms.domain.LinkageType;
import com.qnz.bms.domain.LinkageTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkageTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    long countByExample(LinkageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int deleteByExample(LinkageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int insert(LinkageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int insertSelective(LinkageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    List<LinkageType> selectByExample(LinkageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    LinkageType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LinkageType record, @Param("example") LinkageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LinkageType record, @Param("example") LinkageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LinkageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LinkageType record);
}