package com.qnz.bms.mapper;

import com.qnz.bms.domain.Linkage;
import com.qnz.bms.domain.LinkageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    long countByExample(LinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int deleteByExample(LinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int insert(Linkage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int insertSelective(Linkage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    List<Linkage> selectByExample(LinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    Linkage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Linkage record, @Param("example") LinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Linkage record, @Param("example") LinkageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Linkage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Linkage record);
}