package com.qnz.bms.mapper;

import com.qnz.bms.domain.UserRolePurview;
import com.qnz.bms.domain.UserRolePurviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolePurviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    long countByExample(UserRolePurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int deleteByExample(UserRolePurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int insert(UserRolePurview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int insertSelective(UserRolePurview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    List<UserRolePurview> selectByExample(UserRolePurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    UserRolePurview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRolePurview record, @Param("example") UserRolePurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRolePurview record, @Param("example") UserRolePurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRolePurview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRolePurview record);
}