package com.qnz.bms.domain;

import java.io.Serializable;

public class UserRolePurview implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_purview.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_purview.user_role_id
     *
     * @mbg.generated
     */
    private Integer userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_purview.purview_id
     *
     * @mbg.generated
     */
    private Integer purviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_purview.id
     *
     * @return the value of user_role_purview.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_purview.id
     *
     * @param id the value for user_role_purview.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_purview.user_role_id
     *
     * @return the value of user_role_purview.user_role_id
     *
     * @mbg.generated
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_purview.user_role_id
     *
     * @param userRoleId the value for user_role_purview.user_role_id
     *
     * @mbg.generated
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_purview.purview_id
     *
     * @return the value of user_role_purview.purview_id
     *
     * @mbg.generated
     */
    public Integer getPurviewId() {
        return purviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_purview.purview_id
     *
     * @param purviewId the value for user_role_purview.purview_id
     *
     * @mbg.generated
     */
    public void setPurviewId(Integer purviewId) {
        this.purviewId = purviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserRolePurview other = (UserRolePurview) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserRoleId() == null ? other.getUserRoleId() == null : this.getUserRoleId().equals(other.getUserRoleId()))
            && (this.getPurviewId() == null ? other.getPurviewId() == null : this.getPurviewId().equals(other.getPurviewId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_purview
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserRoleId() == null) ? 0 : getUserRoleId().hashCode());
        result = prime * result + ((getPurviewId() == null) ? 0 : getPurviewId().hashCode());
        return result;
    }
}